# Portion of data from moves table to cover M1 and M2 sides of syllabus
move_data = [
    {
        "id": 1,
        "name": "snap punch",
        "code": "RW1",
        "belt_colour": "red white",
        "lesson_plan": 1,
        "related_moves": None,
        "module_combo": "M1_1",
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 2,
        "name": "reverse punch",
        "code": "RW2",
        "belt_colour": "red white",
        "lesson_plan": 1,
        "related_moves": None,
        "module_combo": "M1_1, M1_2",
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 3,
        "name": "front kick front leg",
        "code": "RW3",
        "belt_colour": "red white",
        "lesson_plan": 1,
        "related_moves": "RW4",
        "module_combo": "M1_1, M1_23",
        "is_defence": None,
        "is_kick": True,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 4,
        "name": "front kick back leg",
        "code": "RW4",
        "belt_colour": "red white",
        "lesson_plan": 2,
        "related_moves": "RW3",
        "module_combo": "M1_6, M1_11",
        "is_defence": None,
        "is_kick": True,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 5,
        "name": "downward inside deflection front arm",
        "code": "RW5",
        "belt_colour": "red white",
        "lesson_plan": 2,
        "related_moves": "YW12",
        "module_combo": "M1_2",
        "is_defence": "hand",
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 6,
        "name": "backfist front arm",
        "code": "RW6",
        "belt_colour": "red white",
        "lesson_plan": 3,
        "related_moves": "RW7",
        "module_combo": "M1_2, M1_23",
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 7,
        "name": "backfist back arm",
        "code": "RW7",
        "belt_colour": "red white",
        "lesson_plan": 3,
        "related_moves": "RW6",
        "module_combo": "M1_3",
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 8,
        "name": "roundhouse kick back leg",
        "code": "RW8",
        "belt_colour": "red white",
        "lesson_plan": 3,
        "related_moves": "RW9, R6",
        "module_combo": "M1_3, M1_6, M1_13",
        "is_defence": None,
        "is_kick": True,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 9,
        "name": "roundhouse kick back leg land forward",
        "code": "RW9",
        "belt_colour": "red white",
        "lesson_plan": 3,
        "related_moves": "RW8, R6",
        "module_combo": "M1_6",
        "is_defence": None,
        "is_kick": True,
        "is_jump": None,
        "notes": None
    },
    {
        "id": 10,
        "name": "palm deflection front arm",
        "code": "RW10",
        "belt_colour": "red white",
        "lesson_plan": 4,
        "related_moves": "RW11",
        "module_combo": "M1_3",
        "is_defence": "hand",
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 11,
        "name": "palm deflection back arm",
        "code": "RW11",
        "belt_colour": "red white",
        "lesson_plan": 4,
        "related_moves": "RW10",
        "module_combo": "M1_21",
        "is_defence": "hand",
        "is_kick": False,
        "is_jump": False,
        "notes": "Back foot doesn't twist."
    },
    {
        "id": 12,
        "name": "turn",
        "code": "RW12",
        "belt_colour": "red white",
        "lesson_plan": 4,
        "related_moves": None,
        "module_combo": None,
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 88,
        "name": "turning backfist",
        "code": "BW1",
        "belt_colour": "blue white",
        "lesson_plan": 1,
        "related_moves": None,
        "module_combo": "M2_1",
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 89,
        "name": "bolo reverse punch",
        "code": "BW2",
        "belt_colour": "blue white",
        "lesson_plan": 1,
        "related_moves": None,
        "module_combo": "M2_4",
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": "Let it go, straight down middle, arm brushes ear."
    },
    {
        "id": 90,
        "name": "hand jam",
        "code": "BW3",
        "belt_colour": "blue white",
        "lesson_plan": 2,
        "related_moves": None,
        "module_combo": None,
        "is_defence": "hand",
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 91,
        "name": "leg jam heel front",
        "code": "BW4",
        "belt_colour": "blue white",
        "lesson_plan": 2,
        "related_moves": "BW5",
        "module_combo": None,
        "is_defence": "leg",
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 92,
        "name": "leg jam heel side",
        "code": "BW5",
        "belt_colour": "blue white",
        "lesson_plan": 2,
        "related_moves": "BW4",
        "module_combo": None,
        "is_defence": "leg",
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 93,
        "name": "jump front kick back leg",
        "code": "BW6",
        "belt_colour": "blue white",
        "lesson_plan": 2,
        "related_moves": "GW2",
        "module_combo": "M2_2",
        "is_defence": None,
        "is_kick": True,
        "is_jump": True,
        "notes": None
    },
    {
        "id": 94,
        "name": "ridgehand strike to groin front arm",
        "code": "BW7",
        "belt_colour": "blue white",
        "lesson_plan": 3,
        "related_moves": "BW8",
        "module_combo": "M2_1",
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": "Shoulder drops down."
    },
    {
        "id": 95,
        "name": "ridgehand strike to groin back arm",
        "code": "BW8",
        "belt_colour": "blue white",
        "lesson_plan": 3,
        "related_moves": "BW7",
        "module_combo": "M2_1",
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": "Shoulder drops down."
    },
    {
        "id": 96,
        "name": "inside crescent kick front leg",
        "code": "BW9",
        "belt_colour": "blue white",
        "lesson_plan": 3,
        "related_moves": "BW10",
        "module_combo": "M2_4",
        "is_defence": None,
        "is_kick": True,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 97,
        "name": "inside crescent kick back leg",
        "code": "BW10",
        "belt_colour": "blue white",
        "lesson_plan": 3,
        "related_moves": "BW9",
        "module_combo": "M2_4",
        "is_defence": None,
        "is_kick": True,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 98,
        "name": "reverse footsweep",
        "code": "BW11",
        "belt_colour": "blue white",
        "lesson_plan": 4,
        "related_moves": None,
        "module_combo": None,
        "is_defence": None,
        "is_kick": False,
        "is_jump": False,
        "notes": None
    },
    {
        "id": 99,
        "name": "forward spinning hook kick",
        "code": "BW12",
        "belt_colour": "blue white",
        "lesson_plan": 4,
        "related_moves": "O10",
        "module_combo": "M2_6",
        "is_defence": None,
        "is_kick": True,
        "is_jump": False,
        "notes": None
    },
]
