Screen:
    MDRaisedButton:
        text: "Light Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        md_bg_color: app.theme_cls.primary_light

    MDRaisedButton:
        text: "Primary Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.1}

    MDRaisedButton:
        text: "Dark Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.3}
        md_bg_color: app.theme_cls.primary_dark

    MDLabel:
        text: 'Get a move'
        font_style: "H5"
        bold: True
        theme_text_color: "Hint"
        font_size: 30
        pos_hint: {"center_x":0.55, "center_y":0.9}
        size_hint: 0.35, 0.15

    MDDropDownItem:
        id: drop_item
        pos_hint: {'center_x': .5, 'center_y': .5}
        text: 'Item'
        on_release: print("Press item")

    MDIcon:
        icon: "home"
        pos_hint: {"center_x": 0.1, "center_y": 0.9}

    MDIcon:
        icon: "home_circle"
        pos_hint: {"center_x": 0.2, "center_y": 0.9}

    MDIcon:
        icon: "home-circle-outline"
        pos_hint: {"center_x": 0.3, "center_y": 0.9}

    MDIcon:
        icon: "cog"
        pos_hint: {"center_x": 0.1, "center_y": 0.8}

    MDIcon:
        icon: "heart"
        pos_hint: {"center_x": 0.2, "center_y": 0.8}

    MDIcon:
        icon: "timer"
        pos_hint: {"center_x": 0.3, "center_y": 0.8}

    MDIcon:
        icon: "alarm"
        pos_hint: {"center_x": 0.1, "center_y": 0.7}

    MDIcon:
        icon: "karate"
        pos_hint: {"center_x": 0.2, "center_y": 0.7}

    MDIcon:
        icon: "kabaddi"
        pos_hint: {"center_x": 0.3, "center_y": 0.7}

    MDIcon:
        icon: "boxing-glove"
        pos_hint: {"center_x": 0.1, "center_y": 0.6}

    MDIcon:
        icon: "mixed-martial-arts"
        pos_hint: {"center_x": 0.2, "center_y": 0.6}

    MDIcon:
        icon: "timer-outline"
        pos_hint: {"center_x": 0.3, "center_y": 0.6}

    MDIcon:
        icon: "star"
        pos_hint: {"center_x": 0.1, "center_y": 0.5}

    MDIcon:
        icon: "star-outline"
        pos_hint: {"center_x": 0.2, "center_y": 0.5}

    MDIcon:
        icon: "heart-outline"
        pos_hint: {"center_x": 0.3, "center_y": 0.5}

    MDIcon:
        icon: "arrow-left-bold"
        pos_hint: {"center_x": 0.1, "center_y": 0.4}

    MDIcon:
        icon: "arrow-right-bold"
        pos_hint: {"center_x": 0.2, "center_y": 0.4}

    MDIcon:
        icon: "arrow-left"
        pos_hint: {"center_x": 0.3, "center_y": 0.4}

    MDIcon:
        icon: "arrow-left-bold-outline"
        pos_hint: {"center_x": 0.1, "center_y": 0.3}

    MDIcon:
        icon: "arrow-right-bold-outline"
        pos_hint: {"center_x": 0.2, "center_y": 0.3}

    MDIcon:
        icon: "arrow-left-bold-circle"
        pos_hint: {"center_x": 0.3, "center_y": 0.3}
