Screen:
    MDRaisedButton:
        text: "Light Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.7}
        md_bg_color: app.theme_cls.primary_light

    MDRaisedButton:
        text: "Primary Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.1}

    MDRaisedButton:
        text: "Dark Button"
        pos_hint: {"center_x": 0.5, "center_y": 0.3}
        md_bg_color: app.theme_cls.primary_dark

    MDDropDownItem:
        id: drop_item
        pos_hint: {'center_x': .5, 'center_y': .5}
        text: 'Item'
        on_release: print("Press item")
